### ISSUE TITLE
basepkg.sh -m MACHINE-MACHINE_ARCH ... failed

### ISSUE THREAD

**Issue by fmlorg** [user340/basepkg#60]
_getarch() cannot resolve $MACHINE-$MACHINE_ARCH (not defined as ALIAS) style 
e.g. -m evbarm-earm
which style is used as architecture names under ftp://${FTP}/pub/NetBSD/NetBSD-8.0/.

fixes;
(1) _getarch() can handle them.

(2) enhance command line options e.g.  --machine ... --machine_arch ...  OR (-m and -a like build.sh)

**Comment by user340** [comment]
Merged.  #62
